LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := gamelogic
LOCAL_CFLAGS    :=  -D_GLIBCXX_PERMIT_BACKWARD_HASH -fexceptions
LOCAL_MODULE_FILENAME := libgamelogic

LOCAL_CPP_EXTENSION := .cc .cpp

LOCAL_SRC_FILES := adventurecpp/main.cpp \
../../Classes/AppDelegate.cpp \
../../Classes/particleSystem/particle_emitters.cpp \
../../Classes/particleSystem/particle_manager.cpp \
../../Classes/Client/HelloWorldScene.cpp \
../../Classes/Client/FrontCoverLayer.cpp \
../../Classes/Client/HeroFighter.cpp \
../../Classes/Client/LuaGameAPI.cpp \
../../Classes/Client/TipMgr.cpp \
../../Classes/Client/lua_tinker.cpp \
../../Classes/Client/AreaItemNode.cpp \
../../Classes/Client/Misc/UserData.cpp \
../../Classes/Client/Misc/MonsterData.cpp \
../../Classes/Client/DressUp/DressUpManager.cpp \
../../Classes/Client/GameManager/XLogicManager.cpp \
../../Classes/Client/GameManager/SpriteDataManager.cpp \
../../Classes/Client/GameManager/InstanceManager.cpp \
../../Classes/Client/GameManager/GameConfigFromLuaManager.cpp \
../../Classes/Client/GameManager/GameDataManager.cpp \
../../Classes/Client/GameManager/MainLandManager.cpp \
../../Classes/Client/GameManager/HeroRoleManager.cpp \
../../Classes/Client/GameManager/TimeManager.cpp \
../../Classes/Client/GameManager/LuaTinkerManager.cpp \
../../Classes/Client/GameManager/ItemUpdateManager.cpp \
../../Classes/Client/GameManager/PvAIManager.cpp \
../../Classes/Client/CharacterSelect/CharacterSelectLayer.cpp \
../../Classes/Client/UILayer/MainMenuLayer.cpp \
../../Classes/Client/UILayer/BattleUILayer.cpp \
../../Classes/Client/UILayer/GameUILayer.cpp \
../../Classes/Client/UILayer/BattleWinLayer.cpp \
../../Classes/Client/UILayer/LoadingLayer.cpp \
../../Classes/Client/UILayer/BackPackLayer.cpp \
../../Classes/Client/UILayer/InstanceListLayer.cpp \
../../Classes/Client/UILayer/CityListLayer.cpp \
../../Classes/Client/UILayer/ItemDragLayer.cpp \
../../Classes/Client/UILayer/EquipmentUpgradeUILayer.cpp \
../../Classes/Client/UILayer/PPVELayer.cpp \
../../Classes/Client/UILayer/PVPLayer.cpp \
../../Classes/Client/UILayer/TalentLayer.cpp \
../../Classes/Client/UILayer/AutoOnHook.cpp \
../../Classes/Client/UILayer/ShopUILayer.cpp \
../../Classes/Client/UILayer/ChatToolbar.cpp \
../../Classes/Client/UILayer/TaskChatLayer.cpp \
../../Classes/Client/UILayer/TaskListLayer.cpp \
../../Classes/Client/UILayer/UIMessageLayer.cpp \
../../Classes/Client/UILayer/WaitingLayer.cpp \
../../Classes/Client/UILayer/MessageBoxLayer.cpp \
../../Classes/Client/UILayer/EquipMixLayer.cpp \
../../Classes/Client/UILayer/AlchemyUILayer.cpp \
../../Classes/Client/UILayer/BattleCoverLayer.cpp\
../../Classes/Client/Items/ItemManager.cpp \
../../Classes/Client/Items/EquipmentItem.cpp \
../../Classes/Client/Items/ItemBase.cpp \
../../Classes/Client/Items/GemStonesFromLua.cpp \
../../Classes/Client/NPC/BoneNPCManager.cpp \
../../Classes/Client/NPC/NpcSprite.cpp \
../../Classes/Client/Task/TaskConfigFromLuaManager.cpp \
../../Classes/Client/Task/TaskData.cpp \
../../Classes/Client/Task/TaskManager.cpp \
../../Classes/Client/UILogic/SkillUI/SkillUIManager.cpp \
../../Classes/Client/Story/StoryDataCenter.cpp \
../../Classes/Client/Story/StoryData.cpp \
../../Classes/Client/Story/InstanceDialogLayer.cpp \
../../Classes/Client/Story/StoryInstanceDirector.cpp \
../../Classes/Client/Monster/SpriteMonsterMgr.cpp \
../../Classes/Client/Monster/MonsterHaozhu.cpp \
../../Classes/Client/Monster/SpriteMonster.cpp \
../../Classes/Client/Monster/SpriteMonsterArcher.cpp \
../../Classes/Client/Monster/MonsterSingleEffect.cpp \
../../Classes/Client/Sprite/SpriteElf.cpp \
../../Classes/Client/Sprite/SpriteElfConfigFromLua.cpp \
../../Classes/Client/Sprite/SpriteElfManager.cpp \
../../Classes/Client/Sprite/ElfChaseState.cpp \
../../Classes/Client/Sprite/ElfCloseToState.cpp \
../../Classes/Client/Sprite/ElfSkillAttackState.cpp \
../../Classes/Client/Sprite/ElfBaseState.cpp \
../../Classes/Client/Sprite/SpriteFactory.cpp \
../../Classes/Client/Sprite/SpriteElfDataCenter.cpp \
../../Classes/Client/Sprite/SpriteElfLayer.cpp \
../../Classes/Client/Sprite/ElfExploreManager.cpp \
../../Classes/Client/ScriptSupport/LuaClient.cpp \
../../Classes/Client/Tutorials/TutorialsManager.cpp \
../../Classes/Client/Tutorials/TutorialsDataCenter.cpp \
../../Classes/Client/Tutorials/TutorialBase.cpp \
../../Classes/Client/Tutorials/UITutorial.cpp \
../../Classes/Client/Tutorials/TutorialLayer.cpp \
../../Classes/Engine/StateMachine/FabstractTransition.cpp \
../../Classes/Engine/StateMachine/FStateMachine.cpp \
../../Classes/Engine/StateMachine/IdleState.cpp \
../../Classes/Engine/StateMachine/RunState.cpp \
../../Classes/Engine/StateMachine/NormalAttackState.cpp \
../../Classes/Engine/StateMachine/LinkTimeState.cpp \
../../Classes/Engine/StateMachine/BaseAttackState.cpp \
../../Classes/Engine/StateMachine/SpecialAttackState.cpp \
../../Classes/Engine/StateMachine/simplefsm.cpp \
../../Classes/Engine/StateMachine/IronDefenseState.cpp \
../../Classes/Engine/StateMachine/InvincibilityState.cpp \
../../Classes/Engine/StateMachine/ApocalypseState.cpp \
../../Classes/Engine/StateMachine/AssassinationState.cpp \
../../Classes/Engine/StateMachine/CalvingState.cpp \
../../Classes/Engine/StateMachine/ChopseriesState.cpp \
../../Classes/Engine/StateMachine/ExtremeSpeedState.cpp \
../../Classes/Engine/StateMachine/FatalDarkKnivesState.cpp \
../../Classes/Engine/StateMachine/GreatFireBallState.cpp \
../../Classes/Engine/StateMachine/InvisibleKillerState.cpp \
../../Classes/Engine/StateMachine/TeleportState.cpp \
../../Classes/Engine/Engine.cpp \
../../Classes/Engine/CCShake.cpp \
../../Classes/Engine/Event.cpp \
../../Classes/Engine/GameManager.cpp \
../../Classes/Engine/GameAudioManager.cpp \
../../Classes/Engine/SceneLayer.cpp \
../../Classes/Engine/MapDataManager.cpp \
../../Classes/Engine/NPCManager.cpp \
../../Classes/Engine/NPC.cpp \
../../Classes/Engine/NameBkg.cpp \
../../Classes/Engine/Painter.cpp \
../../Classes/Engine/MineManager.cpp \
../../Classes/Engine/CameraController.cpp \
../../Classes/Engine/Level/LevelManager.cpp \
../../Classes/Engine/Level/LevelLayer.cpp \
../../Classes/Engine/Level/LevelBuilderCreator.cpp \
../../Classes/Engine/Level/LevelBuilderNormalScene.cpp \
../../Classes/Engine/Level/LevelBuilderRoom.cpp \
../../Classes/Engine/Level/BaseLevelBuilder.cpp \
../../Classes/Engine/Level/LevelObjectCreator.cpp \
../../Classes/Engine/Level/Listener/SpriteTranspointListener.cpp \
../../Classes/Engine/Level/Listener/SpriteSeerListener.cpp \
../../Classes/Engine/Level/Listener/SpriteOtherSeerListener.cpp \
../../Classes/Engine/Level/Listener/BaseListener.cpp \
../../Classes/Engine/Level/Listener/SpriteNpcPointListener.cpp \
../../Classes/Engine/Level/LuaLevelCreator.cpp \
../../Classes/Engine/Sprite/TriggerObject.cpp \
../../Classes/Engine/Sprite/SpriteTransPoint.cpp \
../../Classes/Engine/Sprite/SpriteSeer.cpp \
../../Classes/Engine/Sprite/SpriteBase.cpp \
../../Classes/Engine/Sprite/MapObject.cpp \
../../Classes/Engine/Sprite/HSJoystick.cpp \
../../Classes/Engine/Sprite/PhysicsLayer.cpp \
../../Classes/Engine/SASprite/SkeletonAnimRcsManager.cpp \
../../Classes/Engine/SASprite/RoleActorBase.cpp \
../../Classes/Engine/SASprite/RoleBase.cpp \
../../Classes/Engine/SASprite/BoneSpriteBase.cpp \
../../Classes/Engine/SASprite/BoneSpriteMoveable.cpp \
../../Classes/Engine/SASprite/BoneAnimSprite.cpp \
../../Classes/Engine/SkillSys/SkillDispMgr.cpp \
../../Classes/Engine/SkillSys/ABoxAnimation.cpp \
../../Classes/Engine/SkillSys/AttackChecker.cpp \
../../Classes/Engine/Effect/ParticleManager.cpp \
../../Classes/Engine/Effect/HeroParticleListener.cpp \
../../Classes/Engine/Effect/AParticleNode.cpp \
../../Classes/Engine/Effect/DamageValueEffect.cpp \
../../Classes/Engine/Effect/ComboLayer.cpp \
../../Classes/Engine/Effect/EffectSprite.cpp \
../../Classes/Engine/Map/ATLMapInfo.cpp \
../../Classes/Engine/Map/TileMap.cpp \
../../Classes/Engine/Map/ATLMapLayer.cpp \
../../Classes/Engine/Map/ATLObjectInfo.cpp \
../../Classes/Engine/Map/ATLObjectLayer.cpp \
../../Classes/Engine/Localization/Localization.cpp \
../../Classes/Engine/ScriptSupport/LuaEngine.cpp \
../../Classes/Network/OnlineNetworkManager.cpp \
../../Classes/Network/NetWorkUtil.cpp \
../../Classes/Network/MessageUtil.cpp \
../../Classes/Network/MessageCache.cpp \
../../Classes/Network/MessageHandler.cpp \
../../Classes/NetWork/cs_basic.pb.cc \
../../Classes/NetWork/cs_core.pb.cc \
../../Classes/NetWork/cs_battle.pb.cc \
../../Classes/NetWork/db.pb.cc \
../../Classes/NetWork/errcode.pb.cc \
../../Classes/NetWork/LuaNetwork.cpp \
../../Classes/NetWork/PPVEMessage.cpp \
../../Classes/NetWork/PVPMessage.cpp \
../../Classes/NetWork/NetStateChecker.cpp \
../../Classes/NetWork/MessageFilter.cpp \
../../Classes/Server/log.h	\
../../Classes/Server/base/EventHandler.cpp \
../../Classes/Server/base/Pathname.cpp \
../../Classes/Server/base/TimerEvent.cpp \
../../Classes/Server/battlefields/battlefield.cc \
../../Classes/Server/battlefields/battlehandlers.cc \
../../Classes/Server/battlefields/instance.cc \
../../Classes/Server/config/config.cc \
../../Classes/Server/entities/monster.cc \
../../Classes/Server/entities/object.cc \
../../Classes/Server/entities/skill.cc \
../../Classes/Server/frontend/explorer.cc \
../../Classes/Server/frontend/virtualplayer.cc \
../../Classes/Server/proto/protocodec.cc \
../../libs/ASprite/AnimSprite.cpp \
../../libs/ASprite/ASprite.cpp \
../../libs/ASprite/AspriteManager.cpp \
../../libs/ASprite/EnginePlayerManager.cpp \
../../libs/ASprite/GameEnginePlayer.cpp \
../../libs/CrossPlatform/AES.cpp \
../../libs/CrossPlatform/CrossXOS.cpp \
../../libs/CrossPlatform/CSocketUtil.cpp \
../../libs/CrossPlatform/FileUtils.cpp \
../../libs/CrossPlatform/ImageUtil.cpp \
../../libs/CrossPlatform/md5.cpp \
../../libs/CrossPlatform/Thread.cpp \
../../libs/CrossPlatform/util.cpp \
../../libs/CrossPlatform/XPlatformManager.cpp \
../../libs/CrossPlatform/AndroidPlatform/XPlatform.cpp \
../../libs/CrossPlatform/AndroidPlatform/XUIPlatform.cpp \
../../libs/CrossPlatform/AndroidPlatform/IAP/ProductManager.cpp \
../../libs/Flash2Cocos2d-X/CAnimation.cpp \
../../libs/Flash2Cocos2d-X/CArmature.cpp \
../../libs/Flash2Cocos2d-X/CArmatureAniData.cpp \
../../libs/Flash2Cocos2d-X/CBaseNode.cpp \
../../libs/Flash2Cocos2d-X/CBone.cpp \
../../libs/Flash2Cocos2d-X/CBoneAniData.cpp \
../../libs/Flash2Cocos2d-X/CConnectionData.cpp \
../../libs/Flash2Cocos2d-X/CEventFrame.cpp \
../../libs/Flash2Cocos2d-X/CFrameNode.cpp \
../../libs/Flash2Cocos2d-X/CFrameNodeList.cpp \
../../libs/Flash2Cocos2d-X/CMathHelper.cpp \
../../libs/Flash2Cocos2d-X/CProcessBase.cpp \
../../libs/Flash2Cocos2d-X/CTween.cpp \
../../libs/Flash2Cocos2d-X/CTweenNode.cpp \
../../libs/Flash2Cocos2d-X/CXLog.cpp \
../../libs/PageManager/GameResourceManager.cpp \
../../libs/PageManager/ResourceCache.cpp \
../../libs/PageManager/ResourcePage.cpp \
../../libs/PageManager/ResoureUpdate.cpp \
../../libs/PageManager/ResourcePageManager.cpp \
../../libs/PageManager/Resource/ResourcePlistArray.cpp \
../../libs/PageManager/Resource/ResourcePlistDictionary.cpp \
../../libs/PageManager/Resource/ResourceTexture.cpp \
../../libs/PageManager/AssetsManager.cpp \
../../libs/tinyxml/tinystr.cpp \
../../libs/tinyxml/tinyxml.cpp \
../../libs/tinyxml/tinyxmlerror.cpp \
../../libs/tinyxml/tinyxmlparser.cpp \
../../libs/TXGUI/GameFontManager.cpp \
../../libs/TXGUI/UICreator.cpp \
../../libs/TXGUI/UIManager.cpp \
../../libs/TXGUI/LuaTXGUI.cpp \
../../libs/TXGUI/Common/CustomScene.cpp \
../../libs/TXGUI/Common/LayerBase.cpp \
../../libs/TXGUI/Common/ModelLayer.cpp \
../../libs/TXGUI/Common/NiRTTI.cpp \
../../libs/TXGUI/Common/NiStream.cpp \
../../libs/TXGUI/Common/NotificationCenter.cpp \
../../libs/TXGUI/Common/TXAudioEngine.cpp \
../../libs/TXGUI/Common/UILayerBase.cpp \
../../libs/TXGUI/Common/UILayerColorBase.cpp \
../../libs/TXGUI/Common/UIModelLayerBase.cpp \
../../libs/TXGUI/Common/UIMenu.cpp \
../../libs/TXGUI/Common/UIDragLayer.cpp \
../../libs/TXGUI/Common/DragReceiver.cpp \
../../libs/TXGUI/Common/UILabelTTF.cpp \
../../libs/TXGUI/Controls/CCScale9Sprite.cpp \
../../libs/TXGUI/Controls/IconButton.cpp \
../../libs/TXGUI/Controls/ListItemButton.cpp \
../../libs/TXGUI/Controls/NiObject.cpp \
../../libs/TXGUI/Controls/TextInputField.cpp \
../../libs/TXGUI/Controls/UIAnimation.cpp \
../../libs/TXGUI/Controls/UIButton.cpp \
../../libs/TXGUI/Controls/UIButtonToggle.cpp \
../../libs/TXGUI/Controls/UIContainer.cpp \
../../libs/TXGUI/Controls/UIControlBase.cpp \
../../libs/TXGUI/Controls/UILabel.cpp \
../../libs/TXGUI/Controls/UILabelAtlas.cpp \
../../libs/TXGUI/Controls/UILayout.cpp \
../../libs/TXGUI/Controls/UILayoutRenderNode.cpp \
../../libs/TXGUI/Controls/UIPicture.cpp \
../../libs/TXGUI/Controls/UIScrollLayer.cpp \
../../libs/TXGUI/Controls/UIScrollList.cpp \
../../libs/TXGUI/Controls/UIList.cpp \
../../libs/TXGUI/Controls/UIScrollPage.cpp \
../../libs/TXGUI/Controls/UIScrollView.cpp \
../../libs/TXGUI/Controls/UITextInputField.cpp \
../../libs/cocos2dx_support/CCLuaEngine.cpp \
../../libs/cocos2dx_support/Cocos2dxLuaLoader.cpp \
../../libs/cocos2dx_support/LuaCocos2d.cpp \
../../libs/cocos2dx_support/tolua_fix.c

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes \
$(LOCAL_PATH)/../../Classes/particleSystem \
$(LOCAL_PATH)/../../Classes/Client \
$(LOCAL_PATH)/../../Classes/Client/Misc \
$(LOCAL_PATH)/../../Classes/Client/GameManager \
$(LOCAL_PATH)/../../Classes/Client/CharacterSelect \
$(LOCAL_PATH)/../../Classes/Client/UILayer \
$(LOCAL_PATH)/../../Classes/Client/Items \
$(LOCAL_PATH)/../../Classes/Client/NPC \
$(LOCAL_PATH)/../../Classes/Client/Task \
$(LOCAL_PATH)/../../Classes/Client/Story \
$(LOCAL_PATH)/../../Classes/Client/Monster \
$(LOCAL_PATH)/../../Classes/Client/Sprite \
$(LOCAL_PATH)/../../Classes/Client/DressUp \
$(LOCAL_PATH)/../../Classes/Client/ScriptSupport \
$(LOCAL_PATH)/../../Classes/Client/UILogic \
$(LOCAL_PATH)/../../Classes/Client/Tutorials \
$(LOCAL_PATH)/../../Classes/Client/UILogic/SkillUI \
$(LOCAL_PATH)/../../Classes/Engine \
$(LOCAL_PATH)/../../Classes/Engine/Level \
$(LOCAL_PATH)/../../Classes/Engine/Sprite \
$(LOCAL_PATH)/../../Classes/Engine/Effect \
$(LOCAL_PATH)/../../Classes/Engine/Localization \
$(LOCAL_PATH)/../../Classes/Engine/Map \
$(LOCAL_PATH)/../../Classes/Engine/SASprite \
$(LOCAL_PATH)/../../Classes/Engine/SkillSys \
$(LOCAL_PATH)/../../Classes/Engine/StateMachine \
$(LOCAL_PATH)/../../Classes/Engine/Level/Listener \
$(LOCAL_PATH)/../../Classes/Engine/ScriptSupport \
$(LOCAL_PATH)/../../Classes/Network \
$(LOCAL_PATH)/../../Classes/Server \
$(LOCAL_PATH)/../../Classes/Server/frontend \
$(LOCAL_PATH)/../../cocos2dx/scripting/lua/cocos2dx_support \
$(LOCAL_PATH)/../../cocos2dx/scripting/lua/lua \
$(LOCAL_PATH)/../../cocos2dx/scripting/lua/tolua \
$(LOCAL_PATH)/../../cocos2dx/scripting/lua/src \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/include \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/kazmath/include \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/android \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/android/jni \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/third_party/android/prebuilt/libcurl/include/curl \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/third_party/android/prebuilt/libjpeg/include \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/third_party/android/prebuilt/libpng/include \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/third_party/android/prebuilt/libprofiler/include \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/third_party/android/prebuilt/libtiff/include \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/platform/third_party/android/prebuilt/libxml2/include/libxml \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/support \
$(LOCAL_PATH)/../../cocos2dx/cocos2dx/support/zip_support \
$(LOCAL_PATH)/../../cocos2dx/CocosDenshion/include \
$(LOCAL_PATH)/../../libs/PageManager \
$(LOCAL_PATH)/../../libs/PageManager/Resource \
$(LOCAL_PATH)/../../libs/CrossPlatform \
$(LOCAL_PATH)/../../libs/CrossPlatform/AndroidPlatform \
$(LOCAL_PATH)/../../libs/CrossPlatform/AndroidPlatform/IAP \
$(LOCAL_PATH)/../../libs/CrossPlatform/AndroidPlatform/JSON \
$(LOCAL_PATH)/../../libs/CrossPlatform/AndroidPlatform/SFHFKeychainUtils \
$(LOCAL_PATH)/../../libs/cocos2dx_support \
$(LOCAL_PATH)/../../libs/TXGUI \
$(LOCAL_PATH)/../../libs/TXGUI/Common \
$(LOCAL_PATH)/../../libs/TXGUI/Controls \
$(LOCAL_PATH)/../../libs/ASprite \
$(LOCAL_PATH)/../../libs/ASprite/spriteDefine \
$(LOCAL_PATH)/../../libs/tinyxml \
$(LOCAL_PATH)/../../libs/Flash2Cocos2d-X \
$(LOCAL_PATH)/../../libs/ProtoBuf \
$(LOCAL_PATH)/../../libs/ProtoBuf/include \
$(LOCAL_PATH)/../../libs/ProtoBuf/include/google \
$(LOCAL_PATH)/../../libs/ProtoBuf/include/google/protobuf \
$(LOCAL_PATH)/../../libs/ProtoBuf/include/google/protobuf/io \
$(LOCAL_PATH)/../../libs/ProtoBuf/include/google/protobuf/stubs \
$(LOCAL_PATH)/../../libs/ProtoBuf/include/google/protobuf/compiler \
$(LOCAL_PATH)/../../libs/ProtoBuf/include/google/protobuf/compiler/cpp 
					
LOCAL_WHOLE_STATIC_LIBRARIES := cocos2dx_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocosdenshion_static
LOCAL_WHOLE_STATIC_LIBRARIES += box2d_static
LOCAL_WHOLE_STATIC_LIBRARIES += chipmunk_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_extension_static
LOCAL_WHOLE_STATIC_LIBRARIES += protobuf_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_lua_static
LOCAL_WHOLE_STATIC_LIBRARIES += pbc_static
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)

include $(BUILD_SHARED_LIBRARY)

$(call import-module,cocos2dx/cocos2dx)
$(call import-module,cocos2dx/cocos2dx/platform/third_party/android/prebuilt/libcurl)
$(call import-module,cocos2dx/CocosDenshion/android)
$(call import-module,cocos2dx/extensions)
$(call import-module,cocos2dx/external/Box2D)
$(call import-module,cocos2dx/external/chipmunk)
$(call import-module,cocos2dx/scripting/lua/proj.android/jni)
$(call import-module,libs/ProtoBuf/android)
$(call import-module,libs/pbc)